# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
dsn: "postgres://postgres:postgres@127.0.0.1:5432/turelogo?sslmode=disable"

server_port: "8080"

auth0_client_id: "wT04CB6egP6s0j5AJLwhQWQXuGTITV9Z"
auth0_domain: "app82145387.auth0.com"
auth0_callback_url: "location.href"
auth0_api_secret: "04u22rFvGKCaSVGmb8YHduXs7FdBBynRrvl-lFh3dPS7VOlGGqgTDr-FfNHIleX9"
auth0_api_audience: "https://app82145387.auth0.com/api/v2/"
